# Generated by Django 4.2.6 on 2023-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
