# Generated by Django 4.2.3 on 2023-10-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_messagedata_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageData',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
